### ISSUE TITLE
How to generate trained parameters?

### ISSUE THREAD

**Issue by pkdog** [andrefaraujo/videosearch#10]
Hi.
There are a lot of trained parameters' files in the folder.(indexer/global_descriptors/trained_parameters)
I confused about How to generate trained parameters?
(ps:I am a Chinese student. My English is not very good and may not be clearly expressed.)
Thanks. : )

**Comment by andrefaraujo** [comment]
Hi @pkdog , I do not have open-source code for training those parameters at this point, but this should be simple to implement.

There are three types of parameters: GMMs (ie, the files ending with extension "gmm.N", where N denotes the number of Gaussians), PCA parameters (covariance/eigenvectors), and correlation weights (corr_weights). You can see how they are trained in David Chen's PhD dissertation: https://drive.google.com/file/d/0B05praa_NLuYTGwwLVRMRnY2RGM/view (see section 4.1.2 for PCA, section 4.1.3 for GMM and 4.2.2 for correlation weights).

For PCA and GMM, this should be easy to do with the YAEL library: http://yael.gforge.inria.fr/

If you implement something and want to contribute back to this repository, feel free to submit a pull request and I'll be happy to review it. 

Closing this issue for now, but please feel free to re-open it if you need to.

**Comment by pkdog** [comment]
Thanks. I learn a lot from your code and your paper. :+1:
