### ISSUE TITLE
why descriptor doesn't work?

### ISSUE THREAD

**Issue by ghost** [andrefaraujo/videosearch#12]
Hello, first of all thank you very much for your contribution. In your code, you use vlfeat to extract sift feature. now I want to acceleration sift feature extraction process. I use siftgpu algorithm of chang chang wu, and extrac sift feature of images both in database-all and database-queries successfully. but now i find the feature doesn't work well. When I use the vlfeat code to extract sift feature, the final search accuracy is 64%. But when  I uses  siftgpu to extract sift feature, the finally search accuracy is just 6%。can you give some suggestion about this? thank you very much. the database I use is Stanford I2V dataset.

**Comment by andrefaraujo** [comment]
I think it is possible that the siftgpu you are using has different statistics than the original SIFT used throughout the codebase. If this is the case, you should re-train some of the parameters: PCA/GMM. See #10 for pointers.

**Comment by ghost** [comment]
Thank you very much. I will check it now.
