### ISSUE TITLE
videosearch for windows

### ISSUE THREAD

**Issue by anavc94** [andrefaraujo/videosearch#15]
Hello,

is it possible run videosearch in Windows on an easy way? 

I've successfully built VLFEAT but I am facing some issues with YAEL during 'make', so I've downloaded YAEL's version for windows and compile it with Visual Studio.

Any suggestions will be appreciated!
Btw, congrats for this project!

**Comment by andrefaraujo** [comment]
I have not tried it, so I am not sure if it would work out of the box. Feel free to add tips to this thread that others may benefit later.
