### ISSUE TITLE
test_dataset_ground_truth_local.txt ？？？

### ISSUE THREAD

**Issue by isgangzi** [andrefaraujo/videosearch#20]
Hello, can I ask a question? I put a picture in test_query during the test. But the running result is wrong. The problem is in the file test_dataset_ground_truth_local.txt. I want to ask if this file is automatically updated with the query results. If you need to write it by yourself, it ’s not that you lose the meaning of this project

**Comment by andrefaraujo** [comment]
This is the ground-truth file, so you would need to edit it for any new query you have.
