### ISSUE TITLE
about the trained parameters in indexer/global_descriptors/trained_parameters 

### ISSUE THREAD

**Issue by alexyangfox** [andrefaraujo/videosearch#4]
Hey André,   
Your  work is awesome..
But I feel a little confused about the trained parameters ....
Are these parameters (say..PCA eigen vectors) trained from the whole I2V dataset ...
or just the videos that you have listed here?

Best regards..

**Comment by andrefaraujo** [comment]
Thanks!
Actually, these parameters are trained using a different set of images, separate from the I2V dataset.
The training uses the INRIA Holidays, Oxford Buildings and Pasadena Houses datasets.
There are references to these datasets in my MMSYS paper (references 11, 17 and 1 respectively): http://web.stanford.edu/~afaraujo/Araujo_et_al_MMSys_v14.pdf

**Comment by andrefaraujo** [comment]
Just to explain why this is done: it is important that the parameters be trained in a separate dataset, to test if the performance generalizes, and avoid overfitting. In a practical application, one will use a training set that is separate from the actual testing data the application runs on, so this reproduces this scenario.

**Comment by alexyangfox** [comment]
Thank you very much !
