### ISSUE TITLE
fast weighted hamming

### ISSUE THREAD

**Issue by alexyangfox** [andrefaraujo/videosearch#5]
Hey André,

I wonder how you have done the fast weighted hamming distance with pop_count and fast corr weights...
Is there any reference?

I googled weighted hamming distance , I got this paper: LEARNING WEIGHTED HAMMING DISTANCE FOR BINARY DESCRIPTORS..

But unlickiky.. I failed to relate it to your work...

Regards ..

**Comment by andrefaraujo** [comment]
Here's a reference that does something very similar:
D. Chen, S. Tsai, V. Chandrasekhar, G. Takacs, R. Vedantham, R. Grzeszczuk, and B. Girod, "Residual enhanced visual vector as a compact signature for mobile visual search", Signal Processing, Vol. 93, No. 8, August 2013

**Comment by alexyangfox** [comment]
Amazing.....

Almost immediately replied.....

Thank you very much....

Ps: well.... a good sleep makes a man better...
Nightie night....

Pps: it's the noon here.....
