### ISSUE TITLE
 Add -pthread to CPPFLAGS in the makefile

### ISSUE THREAD

**Issue by pkdog** [andrefaraujo/videosearch#8]
I use videosearch in LUbuntu 17.10. When I executed the step 6 by the Quick Start, it occur errors that undefined reference to symbol 'pthread_create@@GLIBC_2.2.5.

I have to  add -pthread to CPPFLAGS in the makefile then it could make successfully.

**Comment by andrefaraujo** [comment]
thanks @pkdog for reporting this here!

I will close this issue, but please feel free to reopen it if necessary
